version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/runtimes/lightgbm"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/runtimes/sklearn"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/runtimes/xgboost"
    schedule:
      interval: "weekly"


  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
