# generated by datamodel-codegen:
#   filename:  dataplane.yaml

from enum import Enum
from typing import Any

from pydantic import ConfigDict, Field, RootModel

from .base import BaseModel


class MetadataServerResponse(BaseModel):
    """Server metadata returned by the v2 inference protocol health endpoint."""

    name: str
    version: str
    extensions: list[str]


class MetadataServerErrorResponse(BaseModel):
    """Error response for server metadata requests."""

    error: str


class RuntimeSecurityMode(Enum):
    """Security mode controlling which model implementations the server allows."""

    PRODUCTION = "PRODUCTION"
    DEVELOPMENT = "DEVELOPMENT"


class MetadataModelErrorResponse(BaseModel):
    """Error response for model metadata requests."""

    error: str


class Parameters(BaseModel):
    """Extensible parameters attached to requests, inputs, or outputs.

    Allows arbitrary extra fields beyond content_type and headers.
    """

    model_config = ConfigDict(
        extra="allow",
    )
    content_type: str | None = None
    headers: dict[str, Any] | None = None


class TensorData(RootModel[list[Any] | Any]):
    """Container for tensor payload data, supporting list-like access."""

    root: list[Any] | Any = Field(..., title="TensorData")

    def __iter__(self):
        return iter(self.root)

    def __getitem__(self, idx):
        return self.root[idx]

    def __len__(self):
        return len(self.root)


class RequestOutput(BaseModel):
    """Specifies a named output the client wants the server to produce."""

    name: str
    parameters: Parameters | None = None


class InferenceErrorResponse(BaseModel):
    """Error response returned when an inference request fails."""

    error: str | None = None


class Datatype(Enum):
    """V2 inference protocol tensor element data types."""

    BOOL = "BOOL"
    UINT8 = "UINT8"
    UINT16 = "UINT16"
    UINT32 = "UINT32"
    UINT64 = "UINT64"
    INT8 = "INT8"
    INT16 = "INT16"
    INT32 = "INT32"
    INT64 = "INT64"
    FP16 = "FP16"
    FP32 = "FP32"
    FP64 = "FP64"
    BYTES = "BYTES"


class RuntimeSecurityResponse(BaseModel):
    """Response describing the server's current security mode and allowed implementations."""

    mode: RuntimeSecurityMode
    allowed_model_implementations: list[str] | None = Field(
        None, description="Allowed model implementations (production mode only)."
    )


class MetadataTensor(BaseModel):
    """Describes the name, type, and shape of a model input or output tensor."""

    name: str
    datatype: Datatype
    shape: list[int]
    parameters: Parameters | None = None


class RequestInput(BaseModel):
    """A single named tensor sent as part of an inference request."""

    name: str
    shape: list[int]
    datatype: Datatype
    parameters: Parameters | None = None
    data: TensorData


class ResponseOutput(BaseModel):
    """A single named tensor returned as part of an inference response."""

    name: str
    shape: list[int]
    datatype: Datatype
    parameters: Parameters | None = None
    data: TensorData


class InferenceResponse(BaseModel):
    """V2 inference response containing one or more output tensors."""

    model_name: str
    model_version: str | None = None
    id: str | None = None
    parameters: Parameters | None = None
    outputs: list[ResponseOutput]


class MetadataModelResponse(BaseModel):
    """Model metadata describing supported versions, platform, and tensor schemas."""

    name: str
    versions: list[str] | None = None
    platform: str
    inputs: list[MetadataTensor] | None = None
    outputs: list[MetadataTensor] | None = None
    parameters: Parameters | None = None


class InferenceRequest(BaseModel):
    """V2 inference request containing one or more input tensors."""

    id: str | None = None
    parameters: Parameters | None = None
    inputs: list[RequestInput]
    outputs: list[RequestOutput] | None = None
