# generated by datamodel-codegen:
#   filename:  model_repository.yaml

from enum import Enum

from pydantic import Field, RootModel

from .base import BaseModel


class RepositoryIndexRequest(BaseModel):
    """Request to list models in the repository, optionally filtered by readiness."""

    ready: bool | None = None


class State(Enum):
    """Lifecycle state of a model in the repository."""

    UNKNOWN = "UNKNOWN"
    READY = "READY"
    UNAVAILABLE = "UNAVAILABLE"
    LOADING = "LOADING"
    UNLOADING = "UNLOADING"


class RepositoryIndexResponseItem(BaseModel):
    """Status of a single model in the repository index."""

    name: str
    version: str | None = None
    state: State
    reason: str


class RepositoryIndexResponse(RootModel[list[RepositoryIndexResponseItem]]):
    """List of all models in the repository, supporting list-like access."""

    root: list[RepositoryIndexResponseItem] = Field(
        ..., title="RepositoryIndexResponse"
    )

    def __iter__(self):
        return iter(self.root)

    def __getitem__(self, idx):
        return self.root[idx]

    def __len__(self):
        return len(self.root)


class RepositoryLoadErrorResponse(BaseModel):
    """Error response returned when a model load request fails."""

    error: str | None = None


class RepositoryUnloadErrorResponse(BaseModel):
    """Error response returned when a model unload request fails."""

    error: str | None = None
