[tox]
isolated_build = true

[testenv]
skip_install = true
setenv =
    TF_USE_LEGACY_KERAS = 1
allowlist_externals = poetry
commands_pre =
    poetry sync
commands =
    python -m pytest {posargs} -n auto \
        {toxinidir}/tests
